### ISSUE TITLE
Issue while using with Ublock Origin

### ISSUE THREAD

**Issue by Adyel** [RaitaroH/KissAnime-DeepDark#1]
Hey,
I encountered this issue today. When I use Ublock Origin (a content blocker extension) with this style some ads slipped through ( `#adsIfrme8` and `#adsIfrme10` ). Why is this happening can you tell?

![screenshot-20](https://user-images.githubusercontent.com/4653623/40838627-e85228be-65c0-11e8-8f92-53546f5aef68.png)

**Comment by RaitaroH** [comment]
:man_facepalming: ah well, kissanime and ublock have never been friends. I honestly gave up on trying to fix those issues when they come up because I refresh the page and they are gone.... no idea why. But I will add those elements to the code if it makes you feel better.

**Comment by RaitaroH** [comment]
For instance I don't even have those...

**Comment by Adyel** [comment]
I turned off the `cosmetic filter` for Kissanime in `Ublock Origin`. It shows properly now.

**Comment by RaitaroH** [comment]
Yeah....
Here is the code I already hide those:
```
	/*Ads*/
	#divFloatLeft, #tab-trending > div:nth-child(1), #divAds2, #divAds1, #divAds, #divFloatRight, #adsIfrme6, div.divCloseBut, #adsIfrme0, #adsIfrme1, #adsIfrme2, #adsIfrme3, #adsIfrme4, #adsIfrme5, #adsIfrme6, #adsIfrme7, #adsIfrme8, #adsIfrme10, #videoAd, .videoAdClose, [id*="BB_S"]
	{
		display: none !important;
	}
```

**Comment by Adyel** [comment]
It seems like it more of Ublock issue. Thanks for quick response :)

**Comment by RaitaroH** [comment]
https://github.com/RaitaroH/KissAnime-DeepDark/commit/4e20a430ebca34684dbfdbb2f5df641adbd830ce
This is the best I can do. Sorry.

**Comment by Adyel** [comment]
Thanks man

**Comment by RaitaroH** [comment]
@Adyel Btw, you might want to crop your avatar a bit better. It quite shows on a dark theme. Don't take it the wrong way :P

Not crop... render (delete the white outline)
